M48
; DRILL file {KiCad 8.0.6} date 2025-01-14T21:12:59+0100
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2025-01-14T21:12:59+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.6
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0591
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0709
%
G90
G05
T1
X4.9594Y-3.0148
X4.9594Y-3.2057
T2
X5.0787Y-3.003
X5.0787Y-3.2175
M30
